#!/bin/bash
main() {
  which bash
  which ssh
  which ifconfig
  which vim
  echo '###################################'
  ls /bin | xargs
  hostname
  echo '###################################'
  echo ABC $@
}
main 2>&1
